gradle:
  image: gradle:4.5-alpine
  working_dir: /home/gradle/project
  volumes:
    - ./:/home/gradle/project
    - ~/.m2:/home/gradle/.m2
    - ~/config:/home/gradle/config
    - ~/.gradle:/home/gradle/.gradle

node:
  image: opendigitaleducation/node
  working_dir: /home/node/app
  volumes:
    - ./:/home/node/app
    - ~/.npm:/.npm
    - ~/config/.gitconfig:/home/node/.gitconfig
    - ~/config/.npmrc:/home/node/.npmrc
    - ~/config/.bowerrc:/home/node/.bowerrc
    - ~/.gradle:/home/node/.gradle
