GRANT USAGE ON SCHEMA zimbra TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA zimbra TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA zimbra TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA zimbra TO "apps";