export enum SERVICE {
    INVALID_REQUEST = "service.INVALID_REQUEST",
    CIRCUIT_BREAKER = "service.CIRCUIT_BREAKER"
}

export enum MAIL {
    INVALID_REQUEST = "mail.INVALID_REQUEST",
    ATTACHMENT_TOO_BIG = "mail.ATTACHMENT_TOO_BIG",
    MESSAGE_TOO_BIG = "mail.MESSAGE_TOO_BIG"
}

export enum QUOTA {
    QUOTA_EXCEEDED = "mail.QUOTA_EXCEEDED"
}
